Feature/gophermart
c0dered273/go-musthave-diploma-tpl pull request #1
Opened 2023-02-21 20:39 UTC by c0dered273

2023-02-24 11:14 UTC, ASPecherkin requested changes
Оставил замечания к работе + надо поправить так, чтобы проходили автотесты - это обязательное условие

2023-02-24 11:14 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	err = repositories.ApplyMigration(logger, cfg)
Если есть возможность , всё что касается инциализации тут - вынести в отдельную функцию тут же 
а в main оставить тотлько приём сигнала, конфигурацию и старт сервера

2023-02-24 11:14 UTC, ASPecherkin commented on internal/handlers/users.go
> +func getUserOrders(logger zerolog.Logger, service services.UsersService) func(w http.ResponseWriter, r *http.Request) {
лучше вынести эти хендлеры в отдельные файлы , которые будут отражать бизнес сущность - пользователь, заказ, баланс , например

2023-02-24 11:14 UTC, ASPecherkin commented on internal/middleware/jwtauth.go
> +type ClaimCtxKey struct{}
не стоит использовать структуру, особенно пустые в качеству ключа для context 
лучше использовать пользовательский тип на основе string

2023-02-24 11:14 UTC, ASPecherkin commented on internal/repositories/migration.go
> +var migrations embed.FS
молодец, что использовал embed.FS для хранения миграций

2023-02-24 11:14 UTC, ASPecherkin commented on internal/repositories/migrations/20230215140548-insert_order_statuses.sql
> +INSERT INTO order_status(name)
так как все эти таблицы тебе нужны для старта приложения - лучше их объеденить в одну миграцию создания всей схемы базы данных

2023-02-24 11:14 UTC, ASPecherkin commented on internal/repositories/migrations/20230215155513-insert_withdrawals_test_data.sql
> +INSERT INTO withdrawals(order_id, user_id, amount, processed_at)
не стоит смешивать миграции для тестов ( загрузку данных) и миграции схемы данных 
если нужны такие файлы для загрузки данных для тестов - лучше их положить рядом с тестами в папку testdata 
это специальная папка в Go для хранения данных для тестов

2023-02-24 11:14 UTC, ASPecherkin commented on internal/repositories/users.go
> +type UserRepository interface {
отлично , что разделили на отедльные репозитории для каждой бизнес сущности

2023-02-24 11:14 UTC, ASPecherkin commented on internal/services/users.go
> +	claim, ok := ctx.Value(middleware.ClaimCtxKey{}).(*models.AuthClaim)
как раз вот так не надо получать значение из контекста по пустой структуре - легко получить коллизию данных

2023-02-27 21:36 UTC, c0dered273 commented on internal/repositories/migrations/20230215140548-insert_order_statuses.sql
> +INSERT INTO order_status(name)
Есть

2023-02-27 21:36 UTC, c0dered273 commented on internal/repositories/migrations/20230215155513-insert_withdrawals_test_data.sql
> +INSERT INTO withdrawals(order_id, user_id, amount, processed_at)
Есть

2023-02-27 21:40 UTC, c0dered273 commented on internal/services/users.go
> +	claim, ok := ctx.Value(middleware.ClaimCtxKey{}).(*models.AuthClaim)
Есть

2023-02-27 21:40 UTC, c0dered273 commented on internal/middleware/jwtauth.go
> +type ClaimCtxKey struct{}
Есть

2023-02-27 21:59 UTC, c0dered273 commented on cmd/gophermart/main.go
> +	err = repositories.ApplyMigration(logger, cfg)
Есть

2023-02-27 22:02 UTC, c0dered273 commented on internal/handlers/users.go
> +func getUserOrders(logger zerolog.Logger, service services.UsersService) func(w http.ResponseWriter, r *http.Request) {
Есть

2023-02-28 07:45 UTC, ASPecherkin requested changes
Все предыдущие замечания исправлены, тесты проходят
Оставил небольшое замечание о panic - оно короткое, нужно поправить и приму работу

2023-02-28 07:45 UTC, ASPecherkin commented on internal/models/error.go
> +		panic(errors.New("status error: failed to cast err to HTTPError"))
здесь не стоит паниковать 
в целом в Go подход такой, что самому выхывать панику не стоит
Обычно паника показывает то, что не предусмотренно stdlib и самим языком 
здесь достаточно просто залогировать ошибку и продолжить работу

как и выше

2023-02-28 09:38 UTC, c0dered273 commented on internal/models/error.go
> +		panic(errors.New("status error: failed to cast err to HTTPError"))
готово

2023-03-01 17:44 UTC, ASPecherkin approved these changes
Все замечания исправлены, принимаю работу

2023-08-27 09:38 UTC, merged